#! /bin/sh
#
#Copyright (c) 2011 QUALCOMM Incorporated.  All Rights Reserved.
#QUALCOMM Proprietary and Confidential.

# netmgrd   init.d script to start the Data Software's netmgrd daemon

set -e

case "$1" in
  start)
        echo -n "Starting netmgrd: "
        start-stop-daemon -S -b -a /usr/bin/netmgrd -- -u /etc/udhcpc.d/udhcpc.script
        echo "done"
        ;;
  stop)
        echo -n "Stopping netmgrd: "
        start-stop-daemon -K -n netmgrd
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage netmgrd { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
