#!/bin/sh
# Starts the USB Android Gadget.

export KERNEL=`uname -r`

case "$1" in
  start)

        case $KERNEL in
          3.*)

		# boot hsusb composition:
		if [ -d /sys/class/android_usb/android0 ]
		then
			/usr/bin/usb/boot_hsusb_composition n
		fi


		# boot hsic composition:
		if [ -d /sys/class/android_usb/android1 ]
		then
			/usr/bin/usb/boot_hsic_composition y
		fi

		;;
          2.*)
                # Nothing to do for 2.x kernels
                ;;
          *)
                # Some other version of kernel?
                ;;
        esac
        ;;

  stop)
        echo "Stopping USB Android Gadget"
        ;;

  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage usb { start | stop | restart}" >&2
        exit 1
        ;;
esac

